### ISSUE TITLE
moonmining prices not being retracted

### ISSUE THREAD

**Issue by ysm1mh** [skiedude/evestructures#16]
hello,  it seems the prices from the moonmining citadels are no longer being retracted from esi and also i noticed that it doesnt show the moon ores no more 

can this be fixed?

**Comment by skiedude** [comment]
The Moon ores and prices are manual inputs, if they are empty, it is because you have not set them. 

If you have an active moon drill running, select that Athanor from the home page, and you should see some input boxes on the bottom where you can input it. 

The API does not provide the moon ores, or prices.

**Comment by ysm1mh** [comment]
then how come i got this?  as no one entered it as only me has access and i didnt add it.

i believe you. dont mistaken me. glitch?

http://prntscr.com/lx5k04

but thx for the response

**Comment by skiedude** [comment]
Someone else has manually inputted it. Its also saves it in between extractions.

SO if you start an extraction and set that information. Then after its done, restart the same athanor, it will reuse those settings.

**Comment by ysm1mh** [comment]
oke thx for the info.. didnt know that
